[workspace]

members = [
    "api",
    "objects",
    "submit",
    "dependencies",
    "test_producer",
    "undo",
    "representations",
    "updates",
    "operations/obj-traits",
    "operations/obj-defs",
    "operations/operations-lib",
    "operations/operations-server"
]