[workspace]

members = [
    "api",
    "objects",
    "submit",
    "dependencies",
    "test_producer",
    "undo",
    "obj_defs/walls",
    "common/math",
    "common/id_gen",
    "representations",
    "updates"
]