[workspace]

members = [
    "api",
    "objects",
    "submit",
    "dependencies",
    "test_producer",
    "undo",
    "common/math",
    "common/id_gen",
    "common/object_state",
    "common/geom",
    "representations",
    "updates",
    "operations"
]