version: '3.7'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  manager:
    image: qnib/plain-kafka-manager:2018-04-25@sha256:8a30ced91432b9b3ef21bc66c4b5635690e1af823684fe6e29ab866d839d10ca
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_HOSTS: "zoo1:2181"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831/udp"
      - "16686:16686"
  redis-objects:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
    ports: 
      - "6379"
  objects:
    build: 
        context: ./
        dockerfile: objects/Cargo.toml
    depends_on: 
        - redis-objects
        - kafka1
        - jaeger
    environment: 
        - RUN_URL=0.0.0.0:6000
        - JAEGER_URL=jaeger:6831
        - REDIS_URL=redis://redis-objects:6379
        - BROKER=kafka1
        - GROUP=object-group
        - TOPIC=ObjectState
        - RUST_LOG=objects
  redis-deps:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
    ports:
      - "6379"
  dependencies:
    build: 
        context: ./
        dockerfile: dependencies/Cargo.toml
    depends_on: 
        - redis-deps
        - kafka1
        - jaeger
    environment: 
        - RUN_URL=0.0.0.0:6000
        - REDIS_URL=redis://redis-deps:6379
        - JAEGER_URL=jaeger:6831
        - BROKER=kafka1
        - GROUP=dep-group
        - TOPIC=ObjectState
        - RUST_LOG=dependencies
  submit:
    build: 
        context: ./
        dockerfile: submit/Cargo.toml
    depends_on: 
        - kafka1
        - jaeger
    environment: 
        - RUN_URL=0.0.0.0:6000
        - JAEGER_URL=jaeger:6831
        - OBJECTS_URL=http://objects:6000
        - DEPENDENCIES_URL=http://dependencies:6000
        - OPERATIONS_URL=http://operations:6000
        - BROKER=kafka1
        - TOPIC=ObjectState
        - RUST_LOG=submit
  redis-undo:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
    ports:
      - "6379"
  undo:
    build: 
        context: ./
        dockerfile: undo/Cargo.toml
    depends_on: 
        - kafka1
        - jaeger
    environment: 
        - RUN_URL=0.0.0.0:6000
        - JAEGER_URL=jaeger:6831
        - REDIS_URL=redis://redis-undo:6379
        - OBJECTS_URL=http://objects:6000
        - BROKER=kafka1
        - GROUP=undoGroup
        - TOPIC=ObjectState
        - RUST_LOG=undo
  geom-kernel:
    build:
        context: ./
        dockerfile: geometry-kernel/geom-server-cxx/Dockerfile
  operations:
    build: 
        context: ./
        dockerfile: operations/operations-server/Cargo.toml
    environment: 
        - RUN_URL=0.0.0.0:6000
        - JAEGER_URL=jaeger:6831
        - GEOM_URL=http://geom-kernel:5000
        - RUST_LOG=operations_server,operations,obj_traits,obj_defs
  representations:
    build: 
        context: ./
        dockerfile: representations/Cargo.toml
    depends_on: 
        - kafka1
        - jaeger
    environment: 
        - BROKER=kafka1
        - JAEGER_URL=jaeger:6831
        - GROUP=reprGroup
        - OBJ_TOPIC=ObjectState
        - REPR_TOPIC=ClientRepresentation
        - OPS_URL=http://operations:6000
        - RUST_LOG=representations
  updates:
    build: 
        context: ./
        dockerfile: updates/Cargo.toml
    depends_on: 
        - kafka1
    environment: 
        - RUN_URL=0.0.0.0:6000
        - BROKER=kafka1
        - GROUP=updatesGroup
        - TOPIC=ClientRepresentation
        - RUST_LOG=updates
    ports:
      - "7000:6000"
  api:
    build: 
        context: ./
        dockerfile: api/Cargo.toml
    depends_on: 
      - jaeger
    environment: 
        - RUN_URL=0.0.0.0:6000
        - JAEGER_URL=jaeger:6831
        - UNDO_URL=http://undo:6000
        - OPS_URL=http://operations:6000
        - SUBMIT_URL=http://submit:6000
        - RUST_LOG=api
    ports:
      - "8080:6000"
  ui-server:
    build:
        context: ./
        dockerfile: ui-server/Cargo.toml
    environment:
        - RUST_LOG=ui_server
    volumes:
        - type: bind
          source: ./ui/dist
          target: /dist
    ports:
        - "80:80"
      
  