version: '2'
services:
  redis-objects:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
    ports: 
      - "6379"
  objects:
    build: 
        context: ./
        dockerfile: objects/Cargo.toml
    depends_on: 
        - redis-objects
    environment: 
        - RUN_URL=0.0.0.0:6001
        - REDIS_URL=redis://redis-objects:6379
        - BROKER=127.0.0.1:9092
        - GROUP=objects_group
        - TOPIC=ObjectState
        - RUST_LOG=info
    ports:
        - "6001:6001"
  redis-deps:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
    ports:
      - "6380"
  dependencies:
    build: 
        context: ./
        dockerfile: dependencies/Cargo.toml
    depends_on: 
        - redis-deps
    environment: 
        - RUN_URL=0.0.0.0:6002
        - REDIS_URL=redis://redis-deps:6380
        - BROKER=127.0.0.1:9092
        - GROUP=deps_group
        - TOPIC=ObjectState
        - RUST_LOG=info
    ports:
        - "6002:6002"
  submit:
    build: 
        context: ./
        dockerfile: submit/Cargo.toml
    depends_on: 
        - objects
        - dependencies
    environment: 
        - RUN_URL=0.0.0.0:6003
        - OBJECTS_URL=http://objects:6001
        - DEPENDENCIES_URL=http://dependencies:6002
        - BROKER=127.0.0.1:9092
        - TOPIC=ObjectState
        - RUST_LOG=info
    ports:
        - "6003:6003"