version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis-objects:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
  objects:
    build: 
        context: ./
        dockerfile: objects/Cargo.toml
    depends_on: 
        - kafka
        - redis-objects
    environment: 
        - RUN_URL=0.0.0.0:6001
        - REDIS_URL=redis://redis-objects:6379
        - BROKER=placeholder
        - GROUP=placeholder
        - CACHE_LENGTH=20
        - RUST_LOG=info
    ports:
        - "6001"
  redis-deps:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"] #disable persistent data
    restart: always
  dependencies:
    build: 
        context: ./
        dockerfile: dependencies/Cargo.toml
    depends_on: 
        - kafka
        - redis-deps
    environment: 
        - RUN_URL=0.0.0.0:6002
        - REDIS_URL=redis://redis-deps:6379
        - BROKER=placeholder
        - GROUP=placeholder
        - CACHE_LENGTH=20
        - RUST_LOG=info
    ports:
        - "6002"